config/routes.rb
Rails.application.routes.draw do

  # Principal
  root  'paginas#principal'
  get   'paginas/:id_hotel', to: 'paginas#info_hotel', as: 'info_hotel'
  
  # Registros
  get   'registro',     to: 'registros#nuevo',    as: 'registro'
  post  'usuarios',     to: 'registros#guardar',  as: 'usuarios' # crear usuarios normales

  # Reservaciones
  get   'reservas/:id_habitacion', to: 'reservas#nueva', as: 'reservas'
  post  'reservas/:id_habitacion', to:  'reservas#guardar'


  # Roles
  get 'roles',              to: 'roles#listar', as: 'roles'
  get 'roles/nuevo',        to: 'roles#nuevo',  as: 'nuevo_rol'
  get 'roles/:id/editar',   to: 'roles#editar', as: 'editar_rol'
  get 'roles/:id',            to: 'roles#mostrar', as: 'rol'

  post    'roles',        to: 'roles#guardar'
  patch   'roles/:id',    to: 'roles#actualizar'
  delete  'roles/:id',    to: 'roles#eliminar'

  # Ciudades
  get   'ciudades',             to: 'ciudades#listar'                  ,  as: 'ciudades'
  get   'ciudades/nuevo',       to: 'ciudades#mostrar_formulario_crear',  as: 'nueva_ciudad'
  get   'ciudades/:id/editar',  to: 'ciudades#editar',                    as: 'editar_ciudad'
  get   'ciudades/:id',         to: 'ciudades#mostrar',                   as: 'ciudad'

  post    'ciudades',       to: 'ciudades#guardar'
  patch   'ciudades/:id',   to: 'ciudades#actualizar'
  # put     'ciudades/:id',   to: 'ciudades#actualizar' # hace lo mismo que el patch (actualizar)
  delete  'ciudades/:id',   to: 'ciudades#eliminar'

  # Hoteles
  get 'hoteles',                      to: 'hoteles#listar', as: 'hoteles'
  get 'hoteles/nuevo',                to: 'hoteles#nuevo',  as: 'nuevo_hotel'
  get 'hoteles/nuevo/:id_ciudad',     to: 'hoteles#nuevo',  as: 'nuevo_hotel_con_ciudad'
  get 'hoteles/:id/editar',           to: 'hoteles#editar', as: 'editar_hotel'

  post    'hoteles',        to: 'hoteles#guardar'
  patch   'hoteles/:id',    to: 'hoteles#actualizar', as: 'hotel'
  delete  'hoteles/:id',    to: 'hoteles#eliminar'

  # Habitaciones

  get 'habitaciones',             to: 'habitaciones#listar',  as: 'habitaciones'
  get 'habitaciones/nueva',       to: 'habitaciones#nueva',   as: 'nueva_habitacion'
  get 'habitaciones/:id',         to: 'habitaciones#mostrar', as: 'habitacion' # Mostrar la info de 1 habitación
  get 'habitaciones/:id/editar',  to: 'habitaciones#editar',  as: 'editar_habitacion'

  post    'habitaciones',            to: 'habitaciones#guardar'
  put     'habitaciones/:id',        to: 'habitaciones#editar' # Hace lo mismo que el PATCH 
  patch   'habitaciones/:id',        to: 'habitaciones#editar' 
  delete  'habitaciones/:id',        to: 'habitaciones#eliminar'
end

app/controllers/habitaciones_controller.rb
class HabitacionesController < ApplicationController
    
    before_action :asignar_habitacion, only: [:mostrar, :editar, :actualizar, :eliminar]
    
    # GET /habitaciones
    def listar
        @habitaciones = Habitacion.all
    end

    # GET /habitaciones/nueva
    def nueva
        @habitacion = Habitacion.new
        @hoteles = Hotel.all
        @texto_boton = "Registrar habitación"
    end

    # GET /habitaciones/:id
    def mostrar
    end

    # GET /habitaciones/:id/editar
    def editar
        @hoteles = Hotel.all
        @texto_boton = "Actualizar habitación"
    end

    # POST /habitaciones
    def guardar
        @habitacion = Habitacion.new(params_habitacion)
        if @habitacion.save
            redirect_to habitaciones_path
        else
            @hoteles = Hotel.all
            @texto_boton = "Registrar habitación"
            render :nueva
        end
    end

    # PATH/PUT /habitaciones/:id
    def actualizar
        @habitacion.nombre          = params_habitacion[:nombre]
        @habitacion.esta_reservada  = params_habitacion[:esta_reservada]
        @habitacion.precio          = params_habitacion[:precio]
        @habitacion.hotel_id        = params_habitacion[:hotel_id]
        if @habitacion.save
            redirect_to habitaciones_path
        else
            @hoteles = Hotel.all
            @texto_boton = "Actualizar habitación"
            render :editar
        end
    end

    # DELETE /habitaciones/:id
    def eliminar
        @habitacion.destroy
        redirect_to habitaciones_path
    end

    private
    def params_habitacion
        return params.require(:habitacion).permit(:nombre, :precio, :esta_reservada, :hotel_id)
    end

    def asignar_habitacion
        @habitacion = Habitacion.find_by(id: params[:id])
    end
end

app/views/habitaciones/_formularios.html.erb
<!-- Los parciales deberían ser independientes/autónomos -->
<!-- NO deberíamos tener variables que comiencen con @ -->
<!-- VARIALES DE CLASE: @habitacion, @hoteles, @texto_boton -->
<!-- VARIALES LOCALES: p_habitacion, p_hoteles, p_texto_boton -->
<%= form_with(model: p_habitacion) do |formulario| %>

    <div class="mb-3">    
        <%= formulario.label        :nombre, class: 'form-label' %>
        <%= formulario.text_field   :nombre, class: 'form-control' %>
        <% if p_habitacion.errors[:nombre].any? %>
            <div class="alert alert-danger" role="alert">
                <%= p_habitacion.errors[:nombre].first %>
            </div>
        <% end %>
    </div>

    <div class="mb-3">    
        <%= formulario.check_box    :esta_reservada, class: 'form-check-input' %>
        <%= formulario.label        :esta_reservada, class: 'form-check-label' %>
        <% if p_habitacion.errors[:esta_reservada].any? %>
            <div class="alert alert-danger" role="alert">
                <%= p_habitacion.errors[:esta_reservada].first %>
            </div>
        <% end %>
    </div>

    <div class="mb-3">    
        <%= formulario.label        :precio, class: 'form-label'  %>
        <%= formulario.number_field :precio, class: 'form-control'  %>
        <% if p_habitacion.errors[:precio].any? %>
            <div class="alert alert-danger" role="alert">
                <%= p_habitacion.errors[:precio].first %>
            </div>
        <% end %>
    </div>

    <div class="mb-3">    
        <%= formulario.label        :hotel_id, class: 'form-label' %>
        <%= formulario.select       :hotel_id,
        options_from_collection_for_select(p_hoteles, :id, :nombre, p_habitacion.hotel_id),
        { include_blank: "Seleccionar un hotel" },
        class: 'form-select' %>
        <% if p_habitacion.errors[:hotel_id].any? %>
            <div class="alert alert-danger" role="alert">
                <%= p_habitacion.errors[:hotel_id].first %>
            </div>
        <% end %>
    </div>


    <%= formulario.submit p_texto_boton %>

<% end %>

app/views/habitaciones/listar.html.erb
<h1>Habitaciones</h1>

<div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <tr>
                <th class="text-center">Id</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Esta Reservada</th>                
                <th>Hotel</th>
                <th class="text-center">Acciones</th>                
            </tr>
            <% @habitaciones.each do |h| %>
            <tr>
                <td class="text-center"> <%= h.id %> </td>
                <td> <%= h.nombre %> </td>
                <td> <%= h.precio %> </td>
                <td> <%= h.esta_reservada %> </td>
                <td> <%= h.hotel.nombre %> </td>
                <td class="text-center"> 
                    <%= link_to "Editar", editar_habitacion_path(h), class: 'btn btn-warning' %> 
                    <%= link_to "Eliminar", habitacion_path(h), class: 'btn btn-danger', method: :delete, data: {confirm: "¿Está seguro que quiere eliminar la habitación? "} %> 
                </td>
            </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/habitaciones/nueva.html.erb
<h2> Registrar una habitación </h2>

<%= render "formulario", p_habitacion: @habitacion, p_hoteles: @hoteles, p_texto_boton: @texto_boton %>