config/routes.rb
Rails.application.routes.draw do

  # Principal
  root  'paginas#principal'
  get   'paginas/:id_hotel', to: 'paginas#info_hotel', as: 'info_hotel'
  
  # Registros
  get   'registro',     to: 'registros#nuevo',    as: 'registro'
  post  'usuarios',     to: 'registros#guardar',  as: 'usuarios' # crear usuarios normales

  # Reservaciones
  get   'reservas/:id_habitacion', to: 'reservas#nueva', as: 'reservas'
  post  'reservas/:id_habitacion', to:  'reservas#guardar'


  # Roles
  get 'roles',              to: 'roles#listar', as: 'roles'
  get 'roles/nuevo',        to: 'roles#nuevo',  as: 'nuevo_rol'
  get 'roles/:id/editar',   to: 'roles#editar', as: 'editar_rol'
  get 'roles/:id',            to: 'roles#mostrar', as: 'rol'

  post    'roles',        to: 'roles#guardar'
  patch   'roles/:id',    to: 'roles#actualizar'
  delete  'roles/:id',    to: 'roles#eliminar'

  # Ciudades
  get   'ciudades',             to: 'ciudades#listar'                  ,  as: 'ciudades'
  get   'ciudades/nuevo',       to: 'ciudades#mostrar_formulario_crear',  as: 'nueva_ciudad'
  get   'ciudades/:id/editar',  to: 'ciudades#editar',                    as: 'editar_ciudad'
  get   'ciudades/:id',         to: 'ciudades#mostrar',                   as: 'ciudad'

  post    'ciudades',       to: 'ciudades#guardar'
  patch   'ciudades/:id',   to: 'ciudades#actualizar'
  # put     'ciudades/:id',   to: 'ciudades#actualizar' # hace lo mismo que el patch (actualizar)
  delete  'ciudades/:id',   to: 'ciudades#eliminar'

  # Hoteles
  get 'hoteles',                      to: 'hoteles#listar', as: 'hoteles'
  get 'hoteles/nuevo',                to: 'hoteles#nuevo',  as: 'nuevo_hotel'
  get 'hoteles/nuevo/:id_ciudad',     to: 'hoteles#nuevo',  as: 'nuevo_hotel_con_ciudad'
  get 'hoteles/:id/editar',           to: 'hoteles#editar', as: 'editar_hotel'

  post    'hoteles',        to: 'hoteles#guardar'
  patch   'hoteles/:id',    to: 'hoteles#actualizar', as: 'hotel'
  delete  'hoteles/:id',    to: 'hoteles#eliminar'

  # Habitaciones

  get 'habitaciones',             to: 'habitaciones#listar',  as: 'habitaciones'
  get 'habitaciones/nueva',       to: 'habitaciones#nueva',   as: 'nueva_habitacion'
  get 'habitaciones/:id',         to: 'habitaciones#mostrar', as: 'habitacion' # Mostrar la info de 1 habitación
  get 'habitaciones/:id/editar',  to: 'habitaciones#editar',  as: 'editar_habitacion'

  post    'habitaciones',            to: 'habitaciones#guardar'
  put     'habitaciones/:id',        to: 'habitaciones#editar' # Hace lo mismo que el PATCH 
  patch   'habitaciones/:id',        to: 'habitaciones#editar' 
  delete  'habitaciones/:id',        to: 'habitaciones#eliminar'
end

app/controllers/roles_controller.rb
# Lógica | Reciben peticiones y devuelven vistas
class RolesController < ApplicationController
    before_action :asignar_rol, only: [:editar, :actualizar, :eliminar]
    # GET /roles
    def listar
        @roles = Rol.all
    end

    # GET /roles/nuevo
    def nuevo
        # MOSTRAR formulario para guardar roles nuevos
        # @mi_nombre = "rene r. clavijo"
        @rol = Rol.new
    end

    # GET /roles/:id/editar
    def editar
        
    end 

    # POST /roles
    def guardar
        # asignando los datos a un nuevo rol
        @nuevo_rol = Rol.new(params_rol)
        if @nuevo_rol.save
            redirect_to roles_path # => /roles
        else
            render :nuevo
        end
    end

    def actualizar
        @rol.rol = params_rol[:rol]
        if @rol.save
            redirect_to roles_path
        else
            render :editar
        end
    end

    def eliminar
        @rol.destroy
        redirect_to roles_path
    end

    private
    def params_rol
        return params.require(:rol).permit(:rol)
    end

    def asignar_rol
        @rol = Rol.find_by(id: params[:id])
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/editar.html.erb
<h1>Editar un rol</h1>

<%= form_with(model: @rol) do |formulario| %>
    <%= formulario.label        :rol %> 
    <%= formulario.text_field   :rol %>

    <%= formulario.submit "Actualizar" %>
<% end %>

<%= link_to "Volver", roles_path %>

app/views/roles/listar.html.erb
<h1>Lista de roles 🤖</h1>

<%= link_to "Nuevo", nuevo_rol_path %>

<table>
    <tr>
        <th>id</th>
        <th>rol</th>
        <th>acciones</th>
    </tr>
<% @roles.each do |rol| %>
    <tr>
        <td><%= rol.id %></td>
        <td><%= rol.rol %></td>
        <td>
            <%= link_to "Editar", editar_rol_path(rol) %>
            <%= link_to "Eliminar", rol_path(rol), method: :delete, data: { confirm: "¿Está seguro que quiere eliminar este rol?" } %>
        </td>
    </tr>
<% end %>
</table>

app/views/roles/nuevo.html.erb
<!-- 

<h2>Aquí crear el formulario para los</h2>
<h3>ROLES</h3>

<p> Etiqueta ruby con igual </p>
<%= @mi_nombre %>

<p> Etiqueta ruby SIN igual </p>
<% @mi_nombre %>

-->

<h1>Crear un nuevo rol</h1>

<%= form_with(model: @rol) do |formulario| %>
    <%= formulario.label        :rol %>
    <%= formulario.text_field   :rol %>

    <%= formulario.submit "Crear" %>
<% end %>

<%= link_to "Volver", roles_path %>