config/routes.rb
Rails.application.routes.draw do

  # Principal
  root  'paginas#principal'
  get   'paginas/:id_hotel', to: 'paginas#info_hotel', as: 'info_hotel'
  
  # Registros
  get   'registro',     to: 'registros#nuevo',    as: 'registro'
  post  'usuarios',     to: 'registros#guardar',  as: 'usuarios' # crear usuarios normales

  # Reservaciones
  get   'reservas/:id_habitacion', to: 'reservas#nueva', as: 'reservas'
  post  'reservas/:id_habitacion', to:  'reservas#guardar'


  # Roles
  get 'roles',              to: 'roles#listar', as: 'roles'
  get 'roles/nuevo',        to: 'roles#nuevo',  as: 'nuevo_rol'
  get 'roles/:id/editar',   to: 'roles#editar', as: 'editar_rol'
  get 'roles/:id',            to: 'roles#mostrar', as: 'rol'

  post    'roles',        to: 'roles#guardar'
  patch   'roles/:id',    to: 'roles#actualizar'
  delete  'roles/:id',    to: 'roles#eliminar'

  # Ciudades
  get   'ciudades',             to: 'ciudades#listar'                  ,  as: 'ciudades'
  get   'ciudades/nuevo',       to: 'ciudades#mostrar_formulario_crear',  as: 'nueva_ciudad'
  get   'ciudades/:id/editar',  to: 'ciudades#editar',                    as: 'editar_ciudad'
  get   'ciudades/:id',         to: 'ciudades#mostrar',                   as: 'ciudad'

  post    'ciudades',       to: 'ciudades#guardar'
  patch   'ciudades/:id',   to: 'ciudades#actualizar'
  # put     'ciudades/:id',   to: 'ciudades#actualizar' # hace lo mismo que el patch (actualizar)
  delete  'ciudades/:id',   to: 'ciudades#eliminar'

  # Hoteles
  get 'hoteles',                      to: 'hoteles#listar', as: 'hoteles'
  get 'hoteles/nuevo',                to: 'hoteles#nuevo',  as: 'nuevo_hotel'
  get 'hoteles/nuevo/:id_ciudad',     to: 'hoteles#nuevo',  as: 'nuevo_hotel_con_ciudad'
  get 'hoteles/:id/editar',           to: 'hoteles#editar', as: 'editar_hotel'

  post    'hoteles',        to: 'hoteles#guardar'
  patch   'hoteles/:id',    to: 'hoteles#actualizar', as: 'hotel'
  delete  'hoteles/:id',    to: 'hoteles#eliminar'

  # Habitaciones

  get 'habitaciones',             to: 'habitaciones#listar',  as: 'habitaciones'
  get 'habitaciones/nueva',       to: 'habitaciones#nueva',   as: 'nueva_habitacion'
  get 'habitaciones/:id',         to: 'habitaciones#mostrar', as: 'habitacion' # Mostrar la info de 1 habitación
  get 'habitaciones/:id/editar',  to: 'habitaciones#editar',  as: 'editar_habitacion'

  post    'habitaciones',            to: 'habitaciones#guardar'
  put     'habitaciones/:id',        to: 'habitaciones#editar' # Hace lo mismo que el PATCH 
  patch   'habitaciones/:id',        to: 'habitaciones#editar' 
  delete  'habitaciones/:id',        to: 'habitaciones#eliminar'
end

app/controllers/ciudades_controller.rb
class CiudadesController < ApplicationController

    before_action :asignar_ciudad, only: [:mostrar, :editar, :actualizar, :eliminar]

    # GET /ciudades
    def listar
        @lista_ciudades = Ciudad.all
    end

    # GET /ciudades/nuevo
    def mostrar_formulario_crear
        @ciudad = Ciudad.new
    end

    # GET /ciudades/:id
    def mostrar
    end

    # GET /ciudades/:id/editar
    def editar
    end

    # POST /ciudades
    def guardar
        # Guardando los datos 💾
        @ciudad = Ciudad.new
        @ciudad.nombre = params_ciudad[:nombre]
        if @ciudad.save
            # redirect_to "/ciudades"
            redirect_to ciudades_path
        else
            render :mostrar_formulario_crear
        end
    end

    # PATH /ciudades/:id
    def actualizar
        @ciudad.nombre = params_ciudad[:nombre]
        if @ciudad.save
            redirect_to ciudades_path
        else
            render :editar
        end
    end

    # DELETE /ciudades/:id
    def eliminar
        @ciudad.destroy
        redirect_to ciudades_path
    rescue
        flash[:error_ciudad] = "No se puede eliminar la ciudad porque hay hoteles registrados en #{@ciudad.nombre}"
        redirect_to ciudades_path
    end

    private # Todo lo que está abajo 👇👇 es PRIVADO
    
    # recuperamos el :id de la URL 📦 y lo buscamos en la base de datos
    def asignar_ciudad
        @ciudad = Ciudad.find_by(id: params[:id])
        puts "ANTES ASIGNAR UNA CIUDAD".center(50, "🚥")
    end

    # extraer los datos del formulario 📦
    def params_ciudad
        return params.require(:ciudad).permit(:nombre)
    end
end

app/views/ciudades/editar.html.erb
<h1>Editar</h1>

<%= form_with(model: @ciudad) do |formulario| %>

    <%= formulario.label        :nombre %>
    <%= formulario.text_field   :nombre %>
    <% if @ciudad.errors[:nombre].any? %>
        <div>
            <%= @ciudad.errors[:nombre].first %>
        </div>
    <% end %>

    <button>Cancelar</button>
    
    <%= formulario.submit "Actualizar" %>
<% end %>

app/views/ciudades/listar.html.erb
<h5 class="mb-3">
    <b>Lista de ciudades</b>
</h5>
<% if flash[:error_ciudad] %>
    <div class="alert alert-warning" role="alert">
        <%= flash[:error_ciudad] %>
    </div>
<% end %>
<div class="card">
    <div class="card-body">

        <table class="table table-hover">
            <% @lista_ciudades.each do |c| %>
                <tr>
                    <td class="text-center">
                        <%= c.id %>
                    </td>            
                    <td class="text-center">
                        <%= link_to c.nombre, ciudad_path(c) %>
                    </td>
                    <td class="text-center">
                        <%= link_to "Editar", editar_ciudad_path(c), class: "btn btn-warning boton-redondeado" %> <!-- /ciudades/4/editar -->
                        <%= link_to "Eliminar", ciudad_path(c), 
                        method: :delete, 
                        class: "btn btn-danger",
                        data: { confirm: "¿Está seguro que quiere eliminar la ciudad?" } %>
                    </td>
                </tr>
            <% end %>


        </table>
    </div>
</div>

app/views/ciudades/mostrar.html.erb
<div class="card mb-3">
    <div class="card-body">
        <h5>
            <%= @ciudad.nombre %>
        </h5>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <% if @ciudad.hoteles.any? %>
            <table class="table">
                <% @ciudad.hoteles.each do |h| %>
                    <tr>
                        <td> <%= h.nombre %> </td>
                        <td>
                            <% h.estrellas.to_i.times do |e| %>
                            ⭐
                            <% end %>
                        </td>
                        <td>
                            Habitaciones <%= h.habitaciones.count %>
                        </td>
                    </tr>
                <% end %>
            </table>
        <% else %>
            SIN HOTELES REGISTRADOS
            <%= link_to "Registrar hotel", nuevo_hotel_con_ciudad_path(@ciudad), class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/ciudades/mostrar_formulario_crear.html.erb
<div class="card">
    <div class="card-body">

        <h3>Registro de una ciudad</h3>

        <%= form_with(model: @ciudad) do |formulario| %>
            
            <div class="mb-3">
                <%= formulario.label :nombre, class: 'form-label' %>
                <!-- <input type="text" id="nombre" name="nombre"> -->
                <%= formulario.text_field :nombre, class: 'form-control' %>
                <% if @ciudad.errors[:nombre].any? %>
                    <div>
                        <%= @ciudad.errors[:nombre].first %>
                    </div>
                <% end %>
            </div>


            <div class="mb-3 text-end">
                <%= link_to "Cancelar", ciudades_path, class: "btn btn-light mr-3" %>
                <%= formulario.submit 'Registrar', class: 'btn btn-primary' %>
            </div>

        <% end %>

    </div>
</div>