config/routes.rb
Rails.application.routes.draw do

  # Principal
  root  'paginas#principal'
  get   'paginas/:id_hotel', to: 'paginas#info_hotel', as: 'info_hotel'
  
  # Registros
  get   'registro',     to: 'registros#nuevo',    as: 'registro'
  post  'usuarios',     to: 'registros#guardar',  as: 'usuarios' # crear usuarios normales

  # Reservaciones
  get   'reservas/:id_habitacion', to: 'reservas#nueva', as: 'reservas'
  post  'reservas/:id_habitacion', to:  'reservas#guardar'


  # Roles
  get 'roles',              to: 'roles#listar', as: 'roles'
  get 'roles/nuevo',        to: 'roles#nuevo',  as: 'nuevo_rol'
  get 'roles/:id/editar',   to: 'roles#editar', as: 'editar_rol'
  get 'roles/:id',            to: 'roles#mostrar', as: 'rol'

  post    'roles',        to: 'roles#guardar'
  patch   'roles/:id',    to: 'roles#actualizar'
  delete  'roles/:id',    to: 'roles#eliminar'

  # Ciudades
  get   'ciudades',             to: 'ciudades#listar'                  ,  as: 'ciudades'
  get   'ciudades/nuevo',       to: 'ciudades#mostrar_formulario_crear',  as: 'nueva_ciudad'
  get   'ciudades/:id/editar',  to: 'ciudades#editar',                    as: 'editar_ciudad'
  get   'ciudades/:id',         to: 'ciudades#mostrar',                   as: 'ciudad'

  post    'ciudades',       to: 'ciudades#guardar'
  patch   'ciudades/:id',   to: 'ciudades#actualizar'
  # put     'ciudades/:id',   to: 'ciudades#actualizar' # hace lo mismo que el patch (actualizar)
  delete  'ciudades/:id',   to: 'ciudades#eliminar'

  # Hoteles
  get 'hoteles',                      to: 'hoteles#listar', as: 'hoteles'
  get 'hoteles/nuevo',                to: 'hoteles#nuevo',  as: 'nuevo_hotel'
  get 'hoteles/nuevo/:id_ciudad',     to: 'hoteles#nuevo',  as: 'nuevo_hotel_con_ciudad'
  get 'hoteles/:id/editar',           to: 'hoteles#editar', as: 'editar_hotel'

  post    'hoteles',        to: 'hoteles#guardar'
  patch   'hoteles/:id',    to: 'hoteles#actualizar', as: 'hotel'
  delete  'hoteles/:id',    to: 'hoteles#eliminar'

  # Habitaciones

  get 'habitaciones',             to: 'habitaciones#listar',  as: 'habitaciones'
  get 'habitaciones/nueva',       to: 'habitaciones#nueva',   as: 'nueva_habitacion'
  get 'habitaciones/:id',         to: 'habitaciones#mostrar', as: 'habitacion' # Mostrar la info de 1 habitación
  get 'habitaciones/:id/editar',  to: 'habitaciones#editar',  as: 'editar_habitacion'

  post    'habitaciones',            to: 'habitaciones#guardar'
  put     'habitaciones/:id',        to: 'habitaciones#editar' # Hace lo mismo que el PATCH 
  patch   'habitaciones/:id',        to: 'habitaciones#editar' 
  delete  'habitaciones/:id',        to: 'habitaciones#eliminar'
end

app/views/layouts/_menu_horizontal.html.erb
<nav class="navbar navbar-light bg-primary fixed-top">
    <div class="container">
        <div class="row w-100 pt-4 pb-4">
    
            <div class="col-2 text-white mb-1">
                <%= link_to "HCampestre🌴", root_path, class: 'text-decoration-none text-white fs-3'%>
            </div>
            
            <div class="col text-center">
            
                <%= form_with(url: "/", method: "get", class: 'row') do |formulario| %>
            
                    <div class="col text-center mb-1">
                        <%= formulario.text_field :busqueda, class: 'form-control', placeholder: "Buscar: hotel o ciudad" %>
                    </div>
                    <div class="col text-center mb-1"> 
                        <%= formulario.submit "Buscar", class: 'btn btn-secondary text-white' %>
                    </div>
                
                <% end %>
            </div>

            <div class="col-2 text-end">
                <% if @usuario %>
                    <%= link_to "👦 #{@usuario.nombre}", "#", class: 'btn btn-primary text-white' %>
                <% else %>
                    <%= link_to "💻 Registrarse", registro_path, class: 'btn btn-primary text-white' %>
                <% end %>
            </div>
        
        </div>        
    </div>
</nav>

app/views/layouts/_menu_vertical.html.erb
<nav class="menu-vertical col-lg-2">
    <div class="container">
            <h4 class="titulo">
                🌴 HCampestre
            </h4>
    </div>
    <div class="container">

        <ul>
            <li class="separador mb-3 mt-3">
                <strong>HOTELES</strong>
            </li>
            <li>
                <%= link_to hoteles_path, class: "opcion" do %>
                    <i class="bi bi-card-checklist"></i>
                    Listar
                <% end %>
            </li>
            <li>
                <%= link_to nuevo_hotel_path, class: "opcion"  do %>
                    <i class="bi bi-plus-circle"></i>
                    Crear
                <% end %>
            </li>
            <li class="separador mb-3 mt-3">
                <strong>HABITACIONES</strong>
            </li>
            <li>
                <%= link_to habitaciones_path, class: "opcion" do %>
                    <i class="bi bi-card-checklist"></i>
                    Listar
                <% end %>
            </li>
            <li>
                <%= link_to nueva_habitacion_path, class: "opcion"  do %>
                    <i class="bi bi-plus-circle"></i>
                    Crear
                <% end %>
            </li>
            <li class="separador mb-3 mt-3">
                <strong>CIUDADES</strong>
            </li>
            <li>
                <%= link_to ciudades_path, class: "opcion" do %>
                    <i class="bi bi-card-checklist"></i>
                    Listar
                <% end %>
            </li>
            <li>
                <%= link_to nueva_ciudad_path, class: "opcion"  do %>
                    <i class="bi bi-plus-circle"></i>
                    Crear
                <% end %>
            </li>
            <li class="separador mb-3 mt-3">
                <strong>ROLES</strong>
            </li>
            <li>
                <%= link_to roles_path, class: "opcion"  do %>
                    <i class="bi bi-card-checklist"></i>
                    Listar
                <% end %>
            </li>
            <li>
                <%= link_to nuevo_rol_path, class: "opcion" do %>
                    <i class="bi bi-plus-circle"></i>
                    Crear
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoteles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Agregando los íconos de bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/menu_vertical" %>
    <div class="col-lg-10 offset-lg-2">
      <div class="container pt-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/layout_cliente.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoteles </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Agregando los íconos de bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/menu_horizontal" %>
    <div class="container mt-5 pt-5">
      <div class="pt-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>